### ISSUE TITLE
这个问题怎么解决

### ISSUE THREAD

**Issue by OxYancy** [Codennnn/prefer-code-style#1]
![image](https://user-images.githubusercontent.com/16508677/202137684-4b5a0934-e683-4321-bf12-cdc7bf6f9ae1.png)
className 过长和图上那个

**Comment by OxYancy** [comment]
![image](https://user-images.githubusercontent.com/16508677/202177107-bc1594f5-20e4-4ceb-b869-efc5b4c798a3.png)
input的问题解决了  

className 过长自动换行没解决

**Comment by Codennnn** [comment]
这是因为受到 `prettier` 的影响，当一行超出指定的最大长度时会[自动换行](https://prettier.io/docs/en/options.html#print-width)。

默认最大长度为 80，但你也可以配置自己的偏好。

```js
const { prettier } = require('prefer-code-style')

module.exports = {
  ...prettier,
  printWidth: 120,  // <-- 在这里指定最大长度。为了更好的可读性，一般推荐在 120 以内。
}
```

**Comment by OxYancy** [comment]
我试了 不起作用

**Comment by OxYancy** [comment]
就是过长了没有自动换行的功能

**Comment by Codennnn** [comment]
首先，不能将 `prettier/prettier` 设为 `off`。

然后，尝试快速修复适合能解决问题。

**Comment by OxYancy** [comment]
![image](https://user-images.githubusercontent.com/16508677/202380476-6161b765-2a80-4ee5-bfae-47d0928d159e.png)
关闭了 但是 classname 还是很长
而且有自动修复 按保存还是回原来的样子了

**Comment by OxYancy** [comment]
![image](https://user-images.githubusercontent.com/16508677/202380731-7d81f9ba-2f39-4068-9d69-58c3e5e97214.png)

**Comment by Codennnn** [comment]
用示例代码来描述一下你期望得到的效果和你实际得到的效果吧，最好还提供一个代码库例子来运行。
